[package]
name = "kernel_schedule"
version = "0.1.0"
edition = "2021"

[package.metadata.kbuild]
enabled = true

[dependencies]
kernel_task = { path = "../kernel_task" }
kernel_irq = { path = "../kernel_irq" }

[features]
CONFIG_SMP = []
CONFIG_PREEMPT = []
